export interface Role {
    name: string;
    ea_id: number;
    is_plus: boolean;
    is_plus_plus: boolean;
}

export const roles: Role[] = [
    { name: "Advanced Forward", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Advanced Forward+", ea_id: 41, is_plus: true, is_plus_plus: false },
    { name: "Advanced Forward++", ea_id: 141, is_plus: false, is_plus_plus: true },
    { name: "Attacking Wingback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Attacking Wingback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Attacking Wingback+", ea_id: 6, is_plus: true, is_plus_plus: false },
    { name: "Attacking Wingback+", ea_id: 10, is_plus: true, is_plus_plus: false },
    { name: "Attacking Wingback++", ea_id: 106, is_plus: false, is_plus_plus: true },
    { name: "Attacking Wingback++", ea_id: 110, is_plus: false, is_plus_plus: true },
    { name: "Ball-Playing Defender", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Ball-Playing Defender+", ea_id: 13, is_plus: true, is_plus_plus: false },
    { name: "Ball-Playing Defender++", ea_id: 113, is_plus: false, is_plus_plus: true },
    { name: "Box-To-Box", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Box-To-Box+", ea_id: 18, is_plus: true, is_plus_plus: false },
    { name: "Box-To-Box++", ea_id: 118, is_plus: false, is_plus_plus: true },
    { name: "Centre-Half", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Centre-Half+", ea_id: 15, is_plus: true, is_plus_plus: false },
    { name: "Centre-Half++", ea_id: 115, is_plus: false, is_plus_plus: true },
    { name: "Deep-Lying Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Deep-Lying Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Deep-Lying Playmaker+", ea_id: 16, is_plus: true, is_plus_plus: false },
    { name: "Deep-Lying Playmaker+", ea_id: 20, is_plus: true, is_plus_plus: false },
    { name: "Deep-Lying Playmaker++", ea_id: 120, is_plus: false, is_plus_plus: true },
    { name: "Deep-Lying Playmaker++", ea_id: 116, is_plus: false, is_plus_plus: true },
    { name: "Defender", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Defender+", ea_id: 11, is_plus: true, is_plus_plus: false },
    { name: "Defender++", ea_id: 111, is_plus: false, is_plus_plus: true },
    { name: "False 9", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "False 9+", ea_id: 43, is_plus: true, is_plus_plus: false },
    { name: "False 9++", ea_id: 143, is_plus: false, is_plus_plus: true },
    { name: "Falseback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Falseback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Falseback+", ea_id: 8, is_plus: true, is_plus_plus: false },
    { name: "Falseback+", ea_id: 4, is_plus: true, is_plus_plus: false },
    { name: "Falseback++", ea_id: 108, is_plus: false, is_plus_plus: true },
    { name: "Falseback++", ea_id: 104, is_plus: false, is_plus_plus: true },
    { name: "Fullback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Fullback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Fullback+", ea_id: 7, is_plus: true, is_plus_plus: false },
    { name: "Fullback+", ea_id: 3, is_plus: true, is_plus_plus: false },
    { name: "Fullback++", ea_id: 107, is_plus: false, is_plus_plus: true },
    { name: "Fullback++", ea_id: 103, is_plus: false, is_plus_plus: true },
    { name: "Goalkeeper", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Goalkeeper+", ea_id: 1, is_plus: true, is_plus_plus: false },
    { name: "Goalkeeper++", ea_id: 101, is_plus: false, is_plus_plus: true },
    { name: "Half-Winger", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Half-Winger", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Half-Winger+", ea_id: 33, is_plus: true, is_plus_plus: false },
    { name: "Half-Winger+", ea_id: 22, is_plus: true, is_plus_plus: false },
    { name: "Half-Winger++", ea_id: 133, is_plus: false, is_plus_plus: true },
    { name: "Half-Winger++", ea_id: 122, is_plus: false, is_plus_plus: true },
    { name: "Holding", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Holding", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Holding+", ea_id: 14, is_plus: true, is_plus_plus: false },
    { name: "Holding+", ea_id: 19, is_plus: true, is_plus_plus: false },
    { name: "Holding++", ea_id: 119, is_plus: false, is_plus_plus: true },
    { name: "Holding++", ea_id: 114, is_plus: false, is_plus_plus: true },
    { name: "Inside Forward", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Inside Forward", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Inside Forward", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Inside Forward", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Inside Forward+", ea_id: 26, is_plus: true, is_plus_plus: false },
    { name: "Inside Forward+", ea_id: 39, is_plus: true, is_plus_plus: false },
    { name: "Inside Forward+", ea_id: 30, is_plus: true, is_plus_plus: false },
    { name: "Inside Forward+", ea_id: 36, is_plus: true, is_plus_plus: false },
    { name: "Inside Forward++", ea_id: 126, is_plus: false, is_plus_plus: true },
    { name: "Inside Forward++", ea_id: 139, is_plus: false, is_plus_plus: true },
    { name: "Inside Forward++", ea_id: 136, is_plus: false, is_plus_plus: true },
    { name: "Inside Forward++", ea_id: 130, is_plus: false, is_plus_plus: true },
    { name: "Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Playmaker+", ea_id: 21, is_plus: true, is_plus_plus: false },
    { name: "Playmaker+", ea_id: 31, is_plus: true, is_plus_plus: false },
    { name: "Playmaker++", ea_id: 131, is_plus: false, is_plus_plus: true },
    { name: "Playmaker++", ea_id: 121, is_plus: false, is_plus_plus: true },
    { name: "Poacher", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Poacher+", ea_id: 42, is_plus: true, is_plus_plus: false },
    { name: "Poacher++", ea_id: 142, is_plus: false, is_plus_plus: true },
    { name: "Shadow Striker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Shadow Striker+", ea_id: 32, is_plus: true, is_plus_plus: false },
    { name: "Shadow Striker++", ea_id: 132, is_plus: false, is_plus_plus: true },
    { name: "Stopper", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Stopper+", ea_id: 12, is_plus: true, is_plus_plus: false },
    { name: "Stopper++", ea_id: 112, is_plus: false, is_plus_plus: true },
    { name: "Sweeper Keeper", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Sweeper Keeper+", ea_id: 2, is_plus: true, is_plus_plus: false },
    { name: "Sweeper Keeper++", ea_id: 102, is_plus: false, is_plus_plus: true },
    { name: "Target Forward", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Target Forward+", ea_id: 44, is_plus: true, is_plus_plus: false },
    { name: "Target Forward++", ea_id: 144, is_plus: false, is_plus_plus: true },
    { name: "Wide Midfielder", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wide Midfielder", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wide Midfielder+", ea_id: 24, is_plus: true, is_plus_plus: false },
    { name: "Wide Midfielder+", ea_id: 28, is_plus: true, is_plus_plus: false },
    { name: "Wide Midfielder++", ea_id: 128, is_plus: false, is_plus_plus: true },
    { name: "Wide Midfielder++", ea_id: 124, is_plus: false, is_plus_plus: true },
    { name: "Wide Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wide Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wide Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wide Playmaker", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wide Playmaker+", ea_id: 29, is_plus: true, is_plus_plus: false },
    { name: "Wide Playmaker+", ea_id: 25, is_plus: true, is_plus_plus: false },
    { name: "Wide Playmaker+", ea_id: 37, is_plus: true, is_plus_plus: false },
    { name: "Wide Playmaker+", ea_id: 40, is_plus: true, is_plus_plus: false },
    { name: "Wide Playmaker++", ea_id: 140, is_plus: false, is_plus_plus: true },
    { name: "Wide Playmaker++", ea_id: 137, is_plus: false, is_plus_plus: true },
    { name: "Wide Playmaker++", ea_id: 125, is_plus: false, is_plus_plus: true },
    { name: "Wide Playmaker++", ea_id: 129, is_plus: false, is_plus_plus: true },
    { name: "Wingback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wingback", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Wingback+", ea_id: 5, is_plus: true, is_plus_plus: false },
    { name: "Wingback+", ea_id: 9, is_plus: true, is_plus_plus: false },
    { name: "Wingback++", ea_id: 109, is_plus: false, is_plus_plus: true },
    { name: "Wingback++", ea_id: 105, is_plus: false, is_plus_plus: true },
    { name: "Winger", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Winger", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Winger", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Winger", ea_id: 0, is_plus: false, is_plus_plus: false },
    { name: "Winger+", ea_id: 23, is_plus: true, is_plus_plus: false },
    { name: "Winger+", ea_id: 27, is_plus: true, is_plus_plus: false },
    { name: "Winger+", ea_id: 35, is_plus: true, is_plus_plus: false },
    { name: "Winger+", ea_id: 38, is_plus: true, is_plus_plus: false },
    { name: "Winger++", ea_id: 127, is_plus: false, is_plus_plus: true },
    { name: "Winger++", ea_id: 123, is_plus: false, is_plus_plus: true },
    { name: "Winger++", ea_id: 135, is_plus: false, is_plus_plus: true },
    { name: "Winger++", ea_id: 138, is_plus: false, is_plus_plus: true },
];
